[ADD] 영화 장바구니 카카오페이 결제 기능 추가
wecode-bootcamp-korea/41-2nd-ShallWe-backend pull request #10
Opened 2023-02-07 04:13 UTC by JongHoB

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
[ADD] 영화 장바구니 카카오페이 결제 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- [ADD] 영화 장바구니 카카오페이 결제 기능 추가
- 테스트 코드 제외

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-07 06:48 UTC, Kang-kyunghun requested changes

2023-02-07 06:48 UTC, Kang-kyunghun commented on api/controllers/orderController.js
> +require("dotenv").config();
제거해 주세요.

2023-02-07 06:48 UTC, Kang-kyunghun commented on api/controllers/orderController.js
> +        approval_url: "http://localhost:3000/myShallWe/orders/pick",
환경변수로 뺴야 될 부분들 전부 빼주세요.

2023-02-08 01:58 UTC, Kang-kyunghun requested changes

2023-02-08 01:58 UTC, Kang-kyunghun commented on api/controllers/orderController.js
> +        quantity: 1,
수량은 무조건 1개인가요?

2023-02-08 01:58 UTC, Kang-kyunghun commented on api/controllers/orderController.js
> +        tax_free_amount: 0,
이 값들도 그냥 0으로 하면 되는 것인가요?

2023-02-08 01:58 UTC, Kang-kyunghun commented on api/controllers/orderController.js
> +  const kakaoPay = await axios.post(
카카오페이만 관리하는 class를 만들어서 사용해보면 어떨까요? 
그래야 나중에 결제 부분만 따로 관리하기도 쉽고 테스트 코드 작성도 쉬워집니다.

2023-02-08 01:58 UTC, Kang-kyunghun commented on api/models/orderDao.js
> +       SELECT ?,meeting_id,counts,price,?,2,?,TRUE FROM carts WHERE id IN (?);
값을 바로 안 넣고 SELECT로 값을 가져오는 이유가 있나요??

2023-02-08 02:02 UTC, JongHoB commented on api/controllers/orderController.js
> +  const kakaoPay = await axios.post(
클래스는 구독 결제 기능 다 추가 되면 리팩토링으로 바꿔보도록 하겠습니다.

2023-02-08 02:03 UTC, JongHoB commented on api/models/orderDao.js
> +       SELECT ?,meeting_id,counts,price,?,2,?,TRUE FROM carts WHERE id IN (?);
주문을 받을 때 cart에 있는 값을 받아서 결제가 진행되기 때문에
cart에 있는 값을 가져와서 저장하려고 했습니다.

2023-02-08 02:05 UTC, JongHoB commented on api/controllers/orderController.js
> +        quantity: 1,
수정하겠습니다

2023-02-08 02:19 UTC, JongHoB commented on api/controllers/orderController.js
> +        tax_free_amount: 0,
수정하였습니다

2023-02-08 07:21 UTC, merged